def fat_loss_male_low_level_workout():
    print('Day 1:')
    print('Cardio - Run 20 minutes;')
    print('Legs - Bodyweight squats 20 reps 5 times;')
    print('Legs - Bodyweight split squats 30 reps 4 times;')
    print('Shoulders - Dumbbell press 15 reps 3 times;')
    print('Shoulders - Lateral raise 15 reps 3 times;')
    print('Abs - Abdominal crunch 20 reps 3 times;')
    print('Cardio - Spinning 20 minutes at high intensity;\n')

    print('Day 2:')
    print('Cardio - Elliptical 20 minutes;')
    print('Chest - Push ups 20 reps 5 times;')
    print('Back - Pull ups machine 20 reps 5 times;')
    print('Biceps - Barbell curl 15 reps 3 times;')
    print('Triceps - Cable push-down 15 reps 3 times;')
    print('Low-back - Superman 20 reps 3 times;')
    print('Cardio - Rowing machine  20 minutes at high intensity;\n')